ccflags-y += -I$(srctree)/subsys/bluetooth

obj-$(CONFIG_BT_H4) += h4.o
obj-$(CONFIG_BT_H5) += h5.o
obj-$(CONFIG_BT_SPI) += spi.o
obj-$(CONFIG_BT_ACTIONS) += acts_hci.o
obj-$(CONFIG_BT_ACTIONS_RAW_HCI) += acts_raw_hci.o
