obj-$(CONFIG_UCGUI) += ucgui/
obj-$(CONFIG_UGUI) += ugui/
obj-$(CONFIG_GUI) += gui.o
obj-$(CONFIG_GUI) += gui_util.o
obj-$(CONFIG_DISPLAY) += ui_manager.o
obj-$(CONFIG_LED_MANAGER) += led_manager.o
obj-$(CONFIG_SEG_LED_MANAGER) += seg_led_manager.o
