ccflags-y += -I${srctree}/subsys/net/ip/

obj-$(CONFIG_CA_MANAGER) += ca_manager.o
obj-$(CONFIG_WIFI_MANAGER) += wifi_manager.o
obj-$(CONFIG_HTTP_HELPER) += http/
obj-$(CONFIG_SOCKET_HELPER) += socket/
obj-$(CONFIG_TCP_HELPER) += tcp/
obj-$(CONFIG_DNS_HELPER) += dns/
obj-$(CONFIG_MQTT_HELPER) += mqtt/
obj-$(CONFIG_WEBSOCKET_HELPER) += websocket/


