ccflags-y += -I${srctree}/include/usb -I${srctree}/subsys/usb

# Control if Feature Unit exists
# ccflags-y += -DAUDIO_SOURCE_HAS_FEATURE_UNIT

obj-$(CONFIG_USB_AUDIO_SOURCESINK) += audio_sourcesink.o