obj-$(CONFIG_AUDIO_OUT_ACTS) += audio_out_acts.o
obj-$(CONFIG_AUDIO_IN_ACTS) += audio_in_acts.o
obj-$(CONFIG_AUDIO_ACTS_UTILS) += audio_acts_utils.o
obj-$(CONFIG_AUDIO_DRV_SHELL) += shell/audio_driver_shell.o
obj-$(CONFIG_SOC_SERIES_WOODPECKER) += phy_woodpecker/
