ZEPHYRINCLUDE += -I$(srctree)/kernel/memory/include

lib-$(CONFIG_APP_USED_MEM_PAGE) += memory/src/page/page_dsp.o memory/src/page/page_init.o memory/src/page/page.o memory/src/page/rom_page.o
lib-$(CONFIG_APP_USED_MEM_PAGE) += memory/src/buddy/buddy.o memory/src/buddy/buddy_dump.o memory/src/buddy/buddy_init.o memory/src/buddy/rom_buddy.o
lib-$(CONFIG_APP_USED_MEM_PAGE) += memory/src/malloc/malloc.o memory/src/malloc/free.o memory/src/malloc/dump.o
