subdir-ccflags-y += -USYS_LOG_DOMAIN -DSYS_LOG_DOMAIN=\"tool\" -USYS_LOG_NO_NEWLINE

obj-$(CONFIG_TOOL) += tool_app_main.o
obj-$(CONFIG_TOOL_ASET) += tool_aset.o
obj-$(CONFIG_TOOL_ASQT) += tool_asqt.o
obj-$(CONFIG_TOOL_ECTT) += tool_ectt.o
obj-$(CONFIG_ACTIONS_ATT) += tool_att.o
