obj-$(CONFIG_FM_TRANSMITTER) += fm_common.o
obj-$(CONFIG_FM_TRANSMITTER) += fm_transmitter.o
obj-$(CONFIG_FM_RECEIVER) += fm_receiver.o
obj-$(CONFIG_FM_QN8027) += qn8027/fm_qn8027.o
obj-$(CONFIG_FM_QN8035) += qn8035/fm_qn8035.o
obj-$(CONFIG_FM_RDA5820) += rda5820/fm_rda5820.o