obj-$(CONFIG_USP) += usp_command.o  usp_communication.o  usp_connect.o  usp_disconnect.o  usp_inquiry.o  usp_open.o  usp_protocol_fsm.o  usp_protocol_init.o  usp_transfer.o \
	crc16_ccitt.o crc8_maxim.o
obj-$(CONFIG_USP) += usp_common.o usp_full_duplex_send.o usp_full_duplex_parse_receive_frame.o usp_full_duplex_receive_state.o usp_full_duplex_transfer_unused.o
