obj-$(CONFIG_HOTPLUG) += hotplug_manager.o
obj-$(CONFIG_LINEIN_HOTPLUG) += hotplug_linein.o
obj-$(CONFIG_CARD_HOTPLUG) += hotplug_card.o
obj-$(CONFIG_CHARGER_HOTPLUG) += hotplug_charger.o
obj-$(CONFIG_USB_HOTPLUG) += hotplug_usb.o
