obj-$(CONFIG_MICROBIT_DISPLAY) += mb_display.o mb_font.o
obj-$(CONFIG_SEG_LED_DISPLAY) += seg_led_display.o
obj-$(CONFIG_ACTS_LCD_DISPLAY) += act_lcd_display.o
obj-$(CONFIG_ACTS_SPI_DISPLAY) += act_spi_lcd_display.o
obj-$(CONFIG_PANEL_GC9306) += panel_gc9306_320x240.o
obj-$(CONFIG_PANEL_ST7789V) += panel_st7789v_320x240.o
obj-$(CONFIG_ACTS_LED_DISPLAY) += act_led_display.o
obj-$(CONFIG_PANEL_SSD1306) += panel_ssd1306_128x64.o