ccflags-y += -I${srctree}/include/usb -I${srctree}/subsys/usb

obj-$(CONFIG_USB_DEVICE_NETWORK) += netusb.o
obj-$(CONFIG_USB_DEVICE_NETWORK_ECM) += function_ecm.o
obj-$(CONFIG_USB_DEVICE_NETWORK_RNDIS) += function_rndis.o
