include $(srctree)/ext/lib/Makefile
include $(srctree)/ext/hal/Makefile
include $(srctree)/ext/fs/Makefile
include $(srctree)/ext/debug/Makefile
ifdef CONFIG_ACTIONS_SDK
include $(srctree)/ext/actions/Makefile
endif