ZEPHYRINCLUDE += -I$(srctree)/lib/utils/include
ZEPHYRINCLUDE += -I$(srctree)/lib/utils/include/stream
ZEPHYRINCLUDE += -I$(srctree)/lib/utils/include/iterator
ZEPHYRINCLUDE += -I$(srctree)/lib/memory/include
obj-y += source/
