#obj-y += bt.o		// use bt_test_sample replace
obj-y += bt_test_sample.o bt_test_data.o
obj-y += gatt.o
obj-$(CONFIG_BT_CTLR) += ll.o
obj-$(CONFIG_BT_CTLR) += ticker.o
obj-$(CONFIG_SOC_FLASH_NRF5) += flash.o
obj-$(CONFIG_BT_SNOOP) += btsnoop.o
