obj-$(CONFIG_AUDIO_OUT_DAC_SUPPORT) +=  phy_audio_dac.o
obj-$(CONFIG_AUDIO_OUT_I2STX0_SUPPORT) += phy_audio_i2stx.o
obj-$(CONFIG_AUDIO_OUT_SPDIFTX_SUPPORT) += phy_audio_spdiftx.o

obj-$(CONFIG_AUDIO_IN_ADC_SUPPORT) += 	phy_audio_adc.o
obj-$(CONFIG_AUDIO_IN_I2SRX0_SUPPORT) += phy_audio_i2srx.o
obj-$(CONFIG_AUDIO_IN_SPDIFRX_SUPPORT) += phy_audio_spdifrx.o
