obj-$(CONFIG_BT_DONGLE_SERVICE) += asdp_core.o asdp_parser.o asdp_service_bt.o asdp_service_dm.o asdp_transfer.o
obj-$(CONFIG_BT_DONGLE_SERVICE) += asdp_system_adaptor.o
obj-$(CONFIG_BT_DONGLE_SERVICE) += asdp_usp_adaptor.o
obj-$(CONFIG_USP_DUPLEX) += usp_manager.o
#obj-$(CONFIG_BT_DONGLE_SERVICE) += asdp_stream_adaptor.o