ccflags-y += -I${srctree}/include/usb
ccflags-y += -I${srctree}/include/drivers

obj-$(CONFIG_USB_DEVICE_STACK) += usb_device.o class/
obj-$(CONFIG_USB_DEVICE_BOS) += bos.o
obj-$(CONFIG_USB_HOST_STACK) += usb_host.o host/
