obj-$(CONFIG_DISK_ACCESS_RAM) += disk_access_ram.o
obj-$(CONFIG_DISK_ACCESS_FLASH) += disk_access_flash.o
obj-$(CONFIG_DISK_ACCESS_USB) += disk_access_usb.o
obj-$(CONFIG_DISK_ACCESS_SD) += disk_access_sd.o
obj-$(CONFIG_DISK_ACCESS_NOR) += disk_access_nor.o
obj-$(CONFIG_DISK_ACCESS_PSRAM) += disk_access_psram.o
