obj-$(CONFIG_INPUT_DEV_ACTS_ADCKEY) += adckey_acts.o
obj-$(CONFIG_INPUT_DEV_ACTS_ONOFF_KEY) += onoff_key_acts.o
obj-$(CONFIG_INPUT_DEV_ACTS_IRKEY) += irkey_acts.o
obj-$(CONFIG_INPUT_DEV_ACTS_ADC_SR) += adcsr_act.o
obj-$(CONFIG_ENCODER_INPUT) += encoder_ec11.o
